### PR TITLE
bump node version to 16

### PR DESCRIPTION
**Pull request by muelli**

### CODE REVIEW

**Comment by catsout** [comment]
https://github.com/flatpak/flatpak-builder-tools/issues/173#issuecomment-741989549

**Comment by muelli** [comment]
The app works. Thanks @catsout.

But there's a big ASAR file, despite electron-builder complaining about the lack of ASAR:

```
Running: yarn run pack-linux dir
FB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/lossless-cut --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/build/lossless-cut-1 --bind-mount=/run/build/lossless-cut=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/build/lossless-cut-1 --build-dir=/run/build/lossless-cut --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1677771815 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=XDG_CACHE_HOME=/run/build/lossless-cut/flatpak-node/cache --env=npm_config_nodedir=/usr/lib/sdk/node18 --env=NPM_CONFIG_LOGLEVEL=info --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin:/usr/lib/sdk/node18/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=64 /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-G97wXT /bin/sh -c 'yarn run pack-linux dir'' on host
  • electron-builder  version=23.6.0 os=5.15.0-47-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=23.1.0 appOutDir=dist/linux-unpacked
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
FB: host_command_exited_cb 1419254 0
```

I wonder how to make it not produce an ASAR file.

@catsout why does this work for you?
https://github.com/flathub/net.cozic.joplin_desktop/blob/8aad869adfc541c07a9284aad33aad59165b1a33/net.cozic.joplin_desktop.yml#L82
The package.json does not define a "dist" target.

**Comment by catsout** [comment]
https://github.com/laurent22/joplin/blob/v2.10.8/packages/app-desktop/package.json#L8

**Comment by muelli** [comment]
hm. Thanks. It's gone from here, though: https://github.com/laurent22/joplin/blob/dev/package.json

What happens to the arguments? Are they simply appended to the target? i.e. `yarn run electronRebuild && npx electron-builder --x64 --config.asar=false --linux --dir`?

**Comment by muelli** [comment]
looks better now.

**Pull request merged**
