### PR TITLE
V3.40.0

### PR DESCRIPTION
**Pull request by muelli**
let's see whether this works.
I doubt it'll run, but let's see.

### CODE REVIEW

**Comment by mifi** [comment]
If youre struggling building ffmpeg, you can have a look at https://github.com/mifi/ffmpeg-build-script/blob/master/build-ffmpeg.sh

this is the script that successfully builds the macos version of ffmpeg for losslesscut

**Comment by muelli** [comment]
bot build no.mifi.losslesscut

**Comment by muelli** [comment]
seems to be working alright :)

phantomjs doesn't like the new runtime. But that's a separate issue.

**Comment by mifi** [comment]
great! good job

**Pull request merged**
